### ISSUE TITLE
Link absent without JavaScript

### ISSUE THREAD

**Issue by nemobis** [italia/cloud.italia.it#5]
In tables like https://cloud.italia.it/marketplace/supplier/market/index_IaaS.html , the "clickable-row" is not clickable (because there is no `a` element linking the sub-page).

A click appears to be doing something only after some JavaScript is loaded from ajax.googleapis.com, but the user has no way to know whether and where to click because the cursor does not change.

Please use normal links for the sake of semantics, usability and accessibility.

**Comment by luciopileggi** [comment]
Thanks @nemobis, looks like a valid issue. The cloud marketplace codebase is not in this repository and is managed by our colleagues at Agid. We contacted them asking for a fix.

**Comment by luciopileggi** [comment]
Agid released an all new cloud marketplace section for cloud.italia.it. Pages are all new and there is an integrated search engine.  @nemobis, you can check it out at this address:  https://cloud.italia.it/marketplace/. I close this issue because it was related to the old pages.

**Comment by nemobis** [comment]
The new version of the URL is 
<https://cloud.italia.it/marketplace/show/all?searchCategory=IaaS>, 
which doesn't load anything at all without JavaScript. So the issue only 
got worse.
